#

In [1]:
%matplotlib inline
%config InlineBackend.figure_format='retina'

In [2]:
from IPython.display import IFrame, HTML, YouTubeVideo
import matplotlib as mpl
from matplotlib import pyplot as plt
from matplotlib.pyplot import GridSpec
import seaborn as sns
import numpy as np

In [3]:
import pandas as pd
import os, sys
import warnings

sns.set();
plt.rcParams['figure.figsize'] = (12, 8)
sns.set_style("darkgrid")
sns.set_context("poster", font_scale=1.3)

warnings.filterwarnings('ignore')

In [11]:
pd.set_option('display.max_rows', 99)
pd.set_option('display.max_columns', 999)

In [6]:
#!conda install qgrid -y

#import qgrid # Put imports at the top
#qgrid.nbinstall(overwrite=True)

In [32]:
df = pd.read_csv('../data/eCO2mix_RTE_energie_A.xls', sep='\t', encoding = "ISO-8859-1")

In [33]:
df.drop('Unnamed: 40', axis=1, inplace=True)

In [34]:
df[df.Territoire == 'France'].head()

,Année,Qualité,Territoire,Production totale,Production nucléaire,Production thermique totale,Production thermique charbon,Production thermique fioul,Production thermique gaz,Production hydraulique,Production éolien,Production solaire,Production bio-énergies,Consommation totale,Grande industrie PME/PMI,"Energie, industrie et agriculture",Agriculture et industrie agroalimentaire,Energies et combustibles minéraux solides,Chime et parachimie,Construction automobile,Métallurgie et mécanique,Minéraux et matériaux,"Papier, carton",Sidérurgie,Autres industries,"Tertiaire, télécom et transports",Transports et télécommunications,Tertiaire,Perte,Particuliers professionels,Particuliers,Professionnels,Solde exportateur,Echanges export,Echanges import,Echanges avec le Royaume-uni,Echanges avec l'Espagne,Echanges avec l'Italie,Echanges avec la Suisse,Echanges avec l'Allemagne et la Belgique
0,2012,Données consolidées,France,541,404,48,17,6,24,63,14,4,5,489,243,138,24,14,21,5,24,9,9,12.0,16,105,15,89,NaN,209,160,49,44,73.0,29.0,6.0,1.0,15.0,17.0,3.0
7,2013,Données définitives,France,550,403,43,19,3,19,75,15,4,7,494,239,132,23,11,20,5,24,9,8,12.0,15,106,15,90,37.0,216,172,44,47,79.0,32.0,10.0,1.0,15.0,16.0,3.0
20,2014,Données définitives,France,540,415,25,8,3,14,68,17,5,7,465,234,131,23,11,20,5,24,9,8,12.0,15,102,15,87,34.0,195,150,45,65,92.0,27.0,15.0,3.0,19.0,16.0,10.0
33,2015,Données définitives,France,546,416,34,8,3,22,59,21,7,7,476,237,131,23,11,20,5,25,9,8,12.0,15,105,15,0,0.0,202,157,45,61,93.0,31.0,14.0,7.0,19.0,13.0,6.0

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 40 columns):
Année                                        40 non-null int64
Qualité                                      40 non-null object
Territoire                                   40 non-null object
Production totale                            40 non-null int64
Production nucléaire                         40 non-null int64
Production thermique totale                  40 non-null int64
Production thermique charbon                 40 non-null int64
Production thermique fioul                   40 non-null int64
Production thermique gaz                     40 non-null int64
Production hydraulique                       40 non-null int64
Production éolien                            40 non-null int64
Production solaire                           40 non-null int64
Production bio-énergies                      40 non-null int64
Consommation totale                          40 non-null int64
Grande industrie PME/PMI                     40 non-null int64
Energie, industrie et agriculture            40 non-null int64
Agriculture et industrie agroalimentaire     40 non-null int64
Energies et combustibles minéraux solides    40 non-null int64
Chime et parachimie                          40 non-null int64
Construction automobile                      40 non-null int64
Métallurgie et mécanique                     40 non-null int64
Minéraux et matériaux                        40 non-null int64
Papier, carton                               40 non-null int64
Sidérurgie                                   38 non-null float64
Autres industries                            40 non-null int64
Tertiaire, télécom et transports             40 non-null int64
Transports et télécommunications             40 non-null int64
Tertiaire                                    40 non-null int64
Perte                                        27 non-null float64
Particuliers professionels                   40 non-null int64
Particuliers                                 40 non-null int64
Professionnels                               40 non-null int64
Solde exportateur                            40 non-null int64
Echanges export                              4 non-null float64
Echanges import                              4 non-null float64
Echanges avec le Royaume-uni                 4 non-null float64
Echanges avec l'Espagne                      4 non-null float64
Echanges avec l'Italie                       4 non-null float64
Echanges avec la Suisse                      4 non-null float64
Echanges avec l'Allemagne et la Belgique     4 non-null float64
dtypes: float64(9), int64(29), object(2)
memory usage: 12.6+ KB

___

In [41]:
dfM = pd.read_csv('../data/eCO2mix_RTE_energie_M.xls', sep='\t', encoding = "ISO-8859-1")

In [42]:
dfM.drop('Unnamed: 22', axis=1, inplace=True)

In [43]:
dfM[dfM.Territoire == 'France'].head()

,Mois,Qualité,Territoire,Production totale,Production nucléaire,Production thermique totale,Production thermique charbon,Production thermique fioul,Production thermique gaz,Production hydraulique,Production éolien,Production solaire,Production bio-énergies,Consommation totale,Solde exportateur,Echanges export,Echanges import,Echanges avec le Royaume-uni,Echanges avec l'Espagne,Echanges avec l'Italie,Echanges aves la Suisse,Echanges avec l'Allemagne et la Belgique
0,2010-01,Données consolidées,France,56542,40313.0,8801,2928.0,1690,4184,6307,688,10,423,56342,-489.0,4295.0,4784.0,-652.0,-358.0,1297.0,1613.0,-2390.0
1,2010-02,Données consolidées,France,50406,36316.0,6822,1893.0,1175,3754,5887,980,16,386,48698,1008.0,4709.0,3700.0,-497.0,-333.0,1628.0,1752.0,-1541.0
2,2010-03,Données consolidées,France,51071,35984.0,7250,1994.0,1275,3981,6204,1175,31,428,48294,2044.0,5506.0,3462.0,-365.0,-360.0,1784.0,2022.0,-1037.0
3,2010-04,Données consolidées,France,41693,31294.0,3568,1489.0,612,1467,5684,731,45,370,38637,2484.0,5196.0,2711.0,67.0,-337.0,1522.0,1900.0,-667.0
4,2010-05,Données consolidées,France,39847,29372.0,2843,1097.0,504,1242,6428,743,54,408,37284,2075.0,5221.0,3145.0,486.0,-147.0,1229.0,1287.0,-780.0

In [63]:
dfM.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 22 columns):
Mois                                        699 non-null object
Qualité                                     699 non-null object
Territoire                                  699 non-null object
Production totale                           699 non-null int64
Production nucléaire                        444 non-null float64
Production thermique totale                 699 non-null int64
Production thermique charbon                495 non-null float64
Production thermique fioul                  699 non-null int64
Production thermique gaz                    699 non-null int64
Production hydraulique                      699 non-null int64
Production éolien                           699 non-null int64
Production solaire                          699 non-null int64
Production bio-énergies                     699 non-null int64
Consommation totale                         699 non-null int64
Solde exportateur                           615 non-null float64
Echanges export                             87 non-null float64
Echanges import                             87 non-null float64
Echanges avec le Royaume-uni                87 non-null float64
Echanges avec l'Espagne                     87 non-null float64
Echanges avec l'Italie                      87 non-null float64
Echanges aves la Suisse                     87 non-null float64
Echanges avec l'Allemagne et la Belgique    87 non-null float64
dtypes: float64(10), int64(9), object(3)
memory usage: 120.2+ KB

___

In [49]:
df_Fr2012 = pd.read_csv('../data/france/eCO2mix_RTE_Annuel-Definitif_2012.xls', sep='\t', encoding = "ISO-8859-1")

In [50]:
df_Fr2012.head()

,Périmètre,Nature,Date,Heures,Consommation,Prévision J-1,Prévision J,Fioul,Charbon,Gaz,Nucléaire,Eolien,Solaire,Hydraulique,Pompage,Bioénergies,Ech. physiques,Taux de Co2,Ech. comm. Angleterre,Ech. comm. Espagne,Ech. comm. Italie,Ech. comm. Suisse,Ech. comm. Allemagne-Belgique,Fioul - TAC,Fioul - Cogén.,Fioul - Autres,Gaz - TAC,Gaz - Cogén.,Gaz - CCG,Gaz - Autres,Hydraulique - Fil de l?eau + éclusée,Hydraulique - Lacs,Hydraulique - STEP turbinage,Bioénergies - Déchets,Bioénergies - Biomasse,Bioénergies - Biogaz
France,Données définitives,2012-01-01,00:00,58315.0,58200.0,58200.0,492.0,25.0,3816.0,52697.0,3588.0,0.0,7922.0,-1139.0,719.0,-9806.0,33.0,-1750,-1200,-862,-2625,-2940,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN
France,Données définitives,2012-01-01,00:15,NaN,57700.0,57550.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données définitives,2012-01-01,00:30,58315.0,57200.0,56900.0,492.0,25.0,3816.0,52697.0,3588.0,0.0,7922.0,-1139.0,719.0,-9806.0,33.0,-1750,-1200,-862,-2625,-2940,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN
France,Données définitives,2012-01-01,00:45,NaN,56200.0,56000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,Données définitives,2012-01-01,01:00,56231.0,55200.0,55100.0,492.0,25.0,3834.0,51747.0,3536.0,0.0,7598.0,-1730.0,721.0,-9993.0,34.0,-1750,-1400,-862,-2625,-2714,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN

In [56]:
df_Fr2012.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35137 entries, France to RTE ne pourra être tenu responsable de l'usage qui pourrait être fait des données mises à disposition, ni en cas de prévisions qui se révèleraient imprécises.
Data columns (total 36 columns):
Périmètre                               35136 non-null object
Nature                                  35136 non-null object
Date                                    35136 non-null object
Heures                                  17568 non-null float64
Consommation                            35136 non-null float64
Prévision J-1                           35136 non-null float64
Prévision J                             17568 non-null float64
Fioul                                   17568 non-null float64
Charbon                                 17568 non-null float64
Gaz                                     17568 non-null float64
Nucléaire                               17568 non-null float64
Eolien                                  17568 non-null float64
Solaire                                 17568 non-null float64
Hydraulique                             17568 non-null float64
Pompage                                 17568 non-null float64
Bioénergies                             17568 non-null float64
Ech. physiques                          17568 non-null float64
Taux de Co2                             17255 non-null object
Ech. comm. Angleterre                   17567 non-null object
Ech. comm. Espagne                      17562 non-null object
Ech. comm. Italie                       17567 non-null object
Ech. comm. Suisse                       17567 non-null object
Ech. comm. Allemagne-Belgique           17568 non-null object
Fioul - TAC                             17568 non-null object
Fioul - Cogén.                          17568 non-null object
Fioul - Autres                          17568 non-null object
Gaz - TAC                               17568 non-null object
Gaz - Cogén.                            17568 non-null object
Gaz - CCG                               17568 non-null object
Gaz - Autres                            17568 non-null object
Hydraulique - Fil de l?eau + éclusée    17568 non-null object
Hydraulique - Lacs                      17568 non-null object
Hydraulique - STEP turbinage            17568 non-null object
Bioénergies - Déchets                   17568 non-null object
Bioénergies - Biomasse                  17568 non-null object
Bioénergies - Biogaz                    0 non-null float64
dtypes: float64(15), object(21)
memory usage: 9.9+ MB